services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
  web:
    build: .
    env_file: [.env]   # create a local .env based on .env.example
    environment:
      DATABASE_URL: postgresql+psycopg2://appuser:apppass@db:5432/appdb
    ports: ["8000:8000"]
    depends_on: [db]
volumes:
  dbdata:
